run:
  build-tags:
    - integration

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      # - octalLiteral
      # - dupImport # https://github.com/go-critic/go-critic/issues/845
      # - wrapperFunc
      # - ifElseChain
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: true
    enable-all: true
  lll:
    line-length: 140
    tab-width: 8
  prealloc:
    for-loops: true

linters:
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomnd
    - testpackage
    - nlreturn
    - gci
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
        - gomnd
        - funlen
        - goerr113
        - lll
        - noctx
    - source: "^//go:generate "
      linters:
        - lll
  max-per-linter: 0
  max-same: 0
